trigger: none

pool:
  vmImage: 'windows-latest'
  
stages:
- stage: Build
  displayName: Build the Solution
  jobs:
  - job: Build
    displayName: Build the Solution
    steps:
    - script: echo "This is the first step to test"
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--output $(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'myWebsiteName'
        
- stage: Run
  displayName: Run the Solution
  jobs:
  - job: Run
    displayName: Run the Solution
    steps:
    - script: echo "This is the first step to test"
    - task: PowerShell@2
      displayName: Run the exe from Powershell Core
      inputs:
        pwsh: true
        workingDirectory: $(Build.ArtifactStagingDirectory)
        targetType: 'inline'
        script: & .\ConsoleAppAzurePipeline.exe