trigger: none

pool:
  vmImage: 'windows-latest'
  
stages:
- stage: Build_Stage
  displayName: Build the Solution
  jobs:
  - job: Build_Job
    displayName: Build the Solution
    steps:
    - script: echo "This is the first step to test"
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--output $(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'myWebsiteName'
        
- stage: Run_Stage
  displayName: Run the Solution
  dependsOn: Build_Stage
  jobs:
  - job: Run_Job
    displayName: Run the Solution
    steps:
    - script: echo "This is the first step to test"
    - task: PowerShell@2
      displayName: Run the exe from Powershell Core
      inputs:
        targetType: 'inline'
        script: '& .\ConsoleAppAzurePipeline.exe'