trigger:
- none

stages:
- stage: Stage
  displayName: "This is Template_Stage Stage"
  jobs:
    - job:
      displayName: "This is Template_Stage Job 1"
      pool: 'windows-latest'
      steps:
      - script: echo "This is Job 1 Step 1"
